routes:
- name: 'Kowalska'
  from: 'Kowalska 190, Wrocław'
  to: 'Kowalska 20, Wrocław'
- name: 'Kowale-Mikołajów'
  from: 'Ełcka 15, Wrocław'
  to: 'Legnicka 48h, Wrocław'
- name: 'Różanka-Kowale'
  from: 'Bezpieczna 75, Wrocław'
  to: 'Ełcka 15, Wrocław'
